version: '3.8'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    volumes:
      - "~/zookeeper_data:/var/lib/zookeeper"
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER="yes"
    volumes:
      - "~/kafka_data:/var/lib/kafka/data"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ~/pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$DB_USER", "-d", "$DB_NAME" ]
      interval: 10s
      timeout: 5s
      retries: 5

  orders: &orders
    profiles:
      - remote
    image: synthao/orders:latest
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      KAFKA_BROKER_URL: kafka:9092
    ports:
      - "4000:4000"
    depends_on:
      database:
        condition: service_healthy
      kafka:
        condition: service_started

  notifier: &notifier
    profiles:
      - remote
    image: synthao/notifier:latest
    environment:
      KAFKA_BROKER_URL: kafka:9092
    ports:
      - "4001:4001"
    depends_on:
      - kafka

  orders-local:
    <<: *orders
    profiles:
      - local
    build: ${DOCKER_IMAGE_ORDERS}

  notifier-local:
    <<: *notifier
    profiles:
      - local
    build: ${DOCKER_IMAGE_NOTIFIER}

volumes:
  zookeeper_data:
  kafka_data:
  pg_data:
